1주차 미션 제출
KyubumJang/frontend-mission pull request #1
Opened 2022-01-09 12:49 UTC by KyubumJang

# 1주차 미션 제출 (장규범)

## 접근 방법

* [완료] 미션 코드를 구현하기 위해서 어떤 생각들을 했는지 정리해보세요.

- 요구사항 파악을 먼저 진행했습니다. 각각에 요구사항들에 대해 어떤 것이 필수로 들어가야하는지 먼저 파악을 했습니다.
- 미션 가이드를 본 뒤 올려진 자료들을 정독했습니다. 수행 가이드에 있는 출제자의 의도와 학습 목표를 중점적으로 미션을 진행했습니다.
- 자료들에 대해 노션에 정리를 진행하였고, 이는 영상으로 노션에 정리된 내용을 간단히나마 담아보려합니다.
- Jira를 사용하여 티켓으로 요구사항들을 체계적으로 하나씩 처리했습니다.
- TDD로 코드를 짜는 방식에 대해 조사하였고, 관련 자료를 가장 많이 찾아봤습니다. 
- github에 커밋을 올릴 때 전에 사용하던 방식으로 커밋을 진행하였습니다.
- 각 기능의 구현에 있어서는 vue 공식문서를 참조하여 진행하였습니다. 따른 외부의 링크들도 몇 개 참조하였습니다.
- 에러가 뜰 경우에는 기본적으로 검색을 한 뒤 대부분 해결이 되었습니다. 그래도 도저히 모르겠을 때는 학교 선배에게 직접 물어보며 해결했습니다.

## 특이사항

* [완료] 구현하면서 궁금했던 점이나, 아쉬웠던 부분이 있으면 적어주세요.
- no-alert의 해결방식에 대해 eslint rule을 수정하는 것이 맞는지 의문이 들었습니다.
- 개인적으로 TDD로 테스트 코드를 짜는 것이 가장 어려웠던 부분이고 이를 잘 수행한 것인지 의문이 조금 들었습니다. 이에 대해 자세하게 공부를 더 했어야 하는 아쉬움이 있습니다.
- 컴포넌트를 어떤 식으로 나눠야 할지 고민을 많이 했습니다. 뷰가 아직 학습이 많이 진행되지 않아 이전에 react에서 사용하면 어떻게 했을까 생각한 뒤 진행했습니다..

## 제출 후 확인

* [완료] 본인의 구현 결과를 `dev` 브랜치에 구현하고, `dev` 브랜치에서 `submission` 브랜치로 PR을 보내주세요.
* [완료] Pull Request 생성 후 Reivewer에 @externship-master 와 @lkaybob 을 추가해주세요.

2022-01-10 08:01 UTC, KyubumJang commented
코드 presentation에서 코드에 대한 설명을 자세히 했어야 했는데, 수행 과정에 초점을 맞춰서 어떤 생각으로 코드를 짠 것인지에 대한 설명이 부족했던 것 같습니다.

 추가적으로 다른 분들이 하신 테스트 코드를 보니 제가 생각한 방식은 너무 단순하게 어떤 과정을 거쳐야겠다 판단한 수준에서 멈춘 것 같습니다.

 TDD 방식과 jest에 대해서 이해도가 많이 부족한 것 같아서 따로 공부 후 차주에는 더 나은 테스트 코드를 작성하도록 노력해보겠습니다.

2022-01-10 08:15 UTC, jambottle requested changes
규범님, 안녕하세요? 같은 그룹으로 배정된 김재원이라고 합니다 😃
Code Presentation 영상과 함께 작성하신 코드 잘 봤습니다!

> 코드를 설명하시는 영상을 보고, 'Jira나 Notion으로 프로젝트를 관리하고 기록하시는 모습'에 감탄했어요-
> 특히 TDD 개념을 이해하시기 위해서 본인만의 용어로 해석하려는 노력이 멋있었습니다!

미션 수행하시느라 고생 많으셨습니다, 앞으로도 파이팅!!

2022-01-10 08:15 UTC, jambottle commented on mission/.eslintrc.js
> +    'no-alert': 'off',
`no-alert` 옵션을 끄고 진행하셨네요. 저도 브라우저에 내장된 알림창을 그대로 사용해볼까 했었는데요.
아래 참고한 공식문서를 보면, 에러 메시지가 뜨는 이유가 나름대로 있더라고요? 🤔 규범님도 한번 참고해보셔요!

**🔍참고**(ESLint Docs): https://eslint.org/docs/rules/no-alert

2022-01-10 08:15 UTC, jambottle commented on mission/src/components/HomeMission.vue
> +      message: this.message,
3번 줄의 Input 태그에서 `v-model` 디렉티브를 활용하여 `message` 데이터와의 **양방향 데이터 바인딩**을 시도하고 있기 때문에 데이터의 초기값을 `placeholder` 속성으로 부여하는 것보다는 여기서 `message: ''`와 같이 설정해주는 게 개인적으로는 더 좋아 보여요-

이 부분에 대해서도 공식문서에 비슷한 예제가 있어서 도움이 되시길 바라며 같이 첨부합니다 👍
**🔍참고**(Vue.js Docs): https://v3.ko.vuejs.org/guide/introduction.html#사용자-입력-핸들링 (두 번째 예제)

2022-01-10 08:15 UTC, jambottle commented on mission/src/components/HomeMission.vue
> +      this.message = this.message.slice(1) + this.message[0];
👍👍

2022-01-10 08:15 UTC, jambottle commented on mission/src/components/HomeMission.vue
> +      this.message = this.message.slice(1) + this.message[0];
생각해보니 `this.message[0]`으로 아주 간단하게 첫 글자를 가져올 수가 있었네요... **Simple is the best ✨**

2022-01-10 08:15 UTC, jambottle commented on mission/src/components/HomeMission.vue
> +    NotificationEvent() {
여기 메서드 이름 시작할 때에 대문자가 쓰였네요?
위의 `rotateMessage`처럼 컨벤션 맞춰주시면 좋을 것 같아요-

2022-01-10 08:15 UTC, jambottle commented on mission/src/views/Home.vue
> +    <HomeMission />
컴포넌트 이름이 좀 더 기능을 설명하는 방향으로 바뀌면 더 좋을 것 같습니다 :-D

2022-01-10 08:15 UTC, jambottle commented on mission/tests/unit/HomeInput.spec.js
> +});
규범님, 제가 보기에는 테스트 코드 작성이 전반적으로 잘못된 것 같아요...🥲

1. 이 테스트 코드가 검증하고자 하는 대상은 `HomeMission.vue` 컴포넌트 파일일 텐데요!
**일단 해당 컴포넌트가 테스트 코드에 import 되지 않아**서 컴포넌트와 테스트 코드들이 서로 연결되지 않았습니다.
2. 결국 테스트 대상과는 무관하게 테스트 코드 내에서 임의의 데이터를 정의하게 되었고,
**'내가 임의로 정해놓은 T/F 값이 True냐 False냐'에 대해 테스트하는 셈**이 된 게 아닐까 싶어요.

2022-01-10 08:15 UTC, jambottle commented on mission/tests/unit/HomeInput.spec.js
> +});
만약 규범님께서 'input란에 메세지를 작성하면, input란의 값이 출력된다'라는 내용을 검증하고 싶으시다면,

> `HomeMission.vue` 파일 내의 `message` 데이터의 값이 생겼을 때, 실제로 그 값이 템플릿 어딘가에 그려지고 있는지를 검증할 수 있도록 테스트 내부의 코드를 바꿔주셔야 할 것 같습니다. (그 전에 일단 `HomeMission.vue` 파일의 import가 필요하구요.)

저도 처음에는 Jest를 어떻게 써야 하나 난감해서 여러 자료들을 들여다보느라 시간을 많이 썼는데요...
그나마 이 강좌가 투입한 시간 대비 가장 Jest를 쉽게 이해할 수 있었던 것 같아 아래에 공유해 드려봅니다 ㅎㅎㅎ

**🔍참고**(YouTube): https://youtube.com/playlist?list=PLZKTXPmaJk8L1xCg_1cRjL5huINlP2JKt (약 1시간 분량)

2022-01-10 08:49 UTC, allegoryj commented
안녕하세요 규범님! 2그룹 정진재입니다.
먼저 노션으로 미션 접근 방식을 정리하시고 code presentation을 진행하셔서 기능 구현 과정을 이해하는데 큰 도움이 되었습니다. 기능들도 깔끔하게 잘 구현하신 것 같아요!
저도 TDD가 처음이라 많이 어려웠는데 함께 차근차근 배워나가면 좋겠습니다. 앞으로도 잘 부탁드립니다:)

2022-01-10 08:50 UTC, allegoryj commented on mission/tests/unit/HomeAlertBtn.spec.js
> +  test('alert창이 뜬다.', () => {
테스트 이름을 구체적으로 적어주셔서 어떤 테스트를 하고자 했는지 이해가 잘 되었습니다.

2022-01-10 08:59 UTC, allegoryj commented on mission/tests/unit/HomeAlertBtn.spec.js
> +
조금 더 구체적으로 input 메세지와 output메세지가 일치하는지 test해보는 것도 좋을 것 같습니다.

2022-01-10 09:48 UTC, christianB053 reviewed
안녕하세요, 규범님.  2조 김현빈입니다.
코딩 공부를 막 시작한 초보자로 도움되는 리뷰를 하지 못한 점 양해 부탁드립니다.
영상을 보면서 미션 수행을 위해 해야 할 것, 공부할 것, 진행한 것 등을 일목요연하게 정리해 놓으신 것이 굉장히 인상 깊었습니다.
그럼 남은 미션도 화이팅하세요! :)

2022-01-10 09:48 UTC, christianB053 commented on mission/src/components/HomeMission.vue
> +      this.message = this.message.slice(1) + this.message[0];
문자열 회전 시키기를 구현하지 못했었는데, this.message.slice(1)로 arr[1]이후 모든 요소 복사하여 반환 후
this.message[0]로 첫 글자를 더해주는 방법도 있다는 것을 배울 수 있었습니다.

2022-01-10 11:22 UTC, ddukddak-kim commented
규범님 안녕하세요 :) 
이번 익스텐션 기간동안 Peer 리뷰를 함께 할 2그룹 김경민 입니다. 
만나서 반가워요~ 😎

이번주 미션 수행하느라 고생 많으셨습니다-!

2022-01-10 12:06 UTC, Soohyeon02 commented
안녕하세요 규범님 이번에 같은 조로 배정된 황수현입니다.
아직 부족한 점이 많지만 함께 미션 수행 열심히 해봤으면 좋겠습니다!
미션 수행하느라 수고 많으셨습니다!

2022-01-10 15:54 UTC, lkaybob reviewed
요구사항은 잘 구현해주셨으나, 테스트 코드 작성 접근 방향을 잘못 잡으셔서 많이 아쉽습니다.

추가자료에서 제시해드린 Vue Test Util의 공식문서 중 Crash Course를 참고하시어 복기해보시는 것을 권장드립니다.

https://next.vue-test-utils.vuejs.org/guide/essentials/a-crash-course.html

2022-01-10 15:54 UTC, lkaybob commented on mission/tests/unit/HomeAlertBtn.spec.js
> +  alertWindowOpen: true,
테스트하는 대상이 잘못되었습니다. 작성해주신 테스트 코드는 boolean 값들에 대해서만 테스트를 하고, 실제 컴포넌트를 테스트하지 않고 있습니다.

2022-01-10 15:54 UTC, lkaybob commented on mission/src/components/HomeMission.vue
> +      alert(`${this.message} ${this.counter}`);
eslintrc.js에서 global하게 disable하는 것보다는 필요한 곳에 부분적으로 disable을 적용하는 것을 권장드립니다.

2022-01-14 09:00 UTC, jambottle commented on mission/.eslintrc.js
> +    'no-alert': 'off',
규범님도 온라인 세션 때 들으셨겠지만, `alert` 함수 관련 에러는...
해당 부분에 `// eslint-disable-next-line no-alert`를 한 줄 추가하는 것만으로도 해결 가능한 것 같습니다!

2022-01-14 09:00 UTC, jambottle commented on mission/tests/unit/HomeInput.spec.js
> +});
_온라인 세션을 듣고 나니까 제가 공유 드린 영상 자료보다는 강사님이 공유해주신 공식문서가 훨씬 좋은 자료 같습니다...^^;;_

**🔍참고**(공식문서): https://next.vue-test-utils.vuejs.org/guide/essentials/a-crash-course.html

2022-01-15 12:09 UTC, merged